POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1haWphVU4iLCJpZCI6IjYyZThmNDQ3YTE5ZGZkZTQ1NTJjMTY5OCIsImlhdCI6MTY1OTQzNTUyNn0.bCoPc2Wm3tJCElb8iMAUEKTTWRbg8p_NFY-4gN3uaKg

{
    "title": "Maijan blogi",
    "author": "Maijan kirjailija",
    "url": "wwwmaijancom",
    "likes": 7
}

###

GET http://localhost:3003/api/blogs


###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "maijaUN",
    "name": "maijaN",
    "password": "salasana"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "maijaUN",
    "password": "salasana"
}

###
DELETE http://localhost:3003/api/blogs/62e8ecc1b2bcd2564f04472f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImvDpHl0dMOkasOkdHVubnVzIiwiaWQiOiI2MmQ1YTkzYmZiZTA1Y2QwMzYxZTVmNDEiLCJpYXQiOjE2NTg4NjU2NTN9.RGh7vwDEVXaMMQOeE4RqqaasgVcZ9D85Dvi8qAlYLmM

